description: Example workflow to exercise pulumi/relay integration

# To use this workflow:
# - add it to your relay account
# - configure a Slack connection called 'my-workspace' 
#   (or change this code to match your real connection's name)
# - add workflow secrets for your pulumi and github accounts 
# - copy the webhook url from the relay UI
# - in your pulumi app repo on github, go to settings->webhooks
# - paste the webhook url and set it to execute on PRs

parameters:
  pulumi_backend_url:
    description: Point at a self-hosted Pulumi backend service
  event_payload:
    description: Payload of webhook event, filled in by trigger
  pulumi_commandline:
    description: What to do - only 'preview' (default) or 'up'
    default: preview

triggers:
  - name: github-events
    source:
      type: webhook
      image: relaysh/github-trigger-event-sink
    binding:
      parameters:
        event_payload: !Data event_payload

steps:
  - name: pulumi-run
    image: relaysh/pulumi-step-run
    spec:
      pulumi_access_token: !Secret pulumi_access_token
      github_token: !Secret github_access_token
      pulumi_backend_url: !Parameter pulumi_backend_url
      event_payload: !Parameter event_payload
      pulumi_commandline: !Parameter pulumi_commandline
  - name: slack-output
    image: relaysh/slack-step-message-send
    spec:
      connection: !Connection { type: slack, name: my-workspace }
      channel: prog-relay-testing
      message: !Output {from: pulumi-run, name: output}
      username: relayerbot
