apiVersion: integration/v1
kind: Step
name: template
version: 1
summary: Pulumi run
description: |
  This is a template for a Pulumi run step

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/pulumi-step-run
