apiVersion: integration/v1
kind: Step
name: pulumi-step-run
version: 1
summary: Run Pulumi
description: |
  This step runs pulumi in a CI-style environment.

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/pulumi-step-run
