apiVersion: integration/v1
kind: Step
name: pulumi-step-run
version: 1
summary: Run Pulumi
description: |
  This step runs pulumi in a CI-style environment.

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#
    type: object
    required:
    - event_payload
    properties:
      pulumi_backend_url:
        type: string
        description: Alternate backend specifier
        default: api.pulumi.io
      event_payload:
        type: string
        description: The complete payload of a github webhook. This must be a string of JSON.
      pulumi_commandline:
        type: string
        description: The commandline to pass through to `pulumi ...`
        default: preview
    additionalProperties: false

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/pulumi-step-run

examples: 
- summary: Run Pulumi
  content:
    apiVersion: v1 
    kind: Step
    name: pulumi-run
    image: relaysh/pulumi-step-run
    spec:
      pulumi_access_token: !Secret pulumi_access_token
      github_token: !Secret github_access_token
      pulumi_backend_url: !Parameter pulumi_backend_url
      event_payload: !Parameter event_payload
      pulumi_commandline: !Parameter pulumi_commandline
      stack: !Parameter pulumi_stack